# Generated by Django 3.1.3 on 2020-12-04 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
