# Generated by Django 3.1.3 on 2020-12-10 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.productinfo'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
