# Generated by Django 3.1.3 on 2020-12-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201211_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='proceed',
            field=models.BooleanField(default=True),
        ),
    ]
