# Generated by Django 3.1.3 on 2020-12-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_orderitem_proceed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='ordered',
            field=models.BooleanField(default=None),
        ),
    ]
