# Generated by Django 3.1.3 on 2020-12-24 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201224_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoughtItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.orderitem')),
            ],
        ),
    ]
