# Generated by Django 3.1.3 on 2020-12-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_boughtitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
