# Generated by Django 3.1.3 on 2020-12-25 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_boughtitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productinfo'),
        ),
    ]
