# Generated by Django 3.1.3 on 2020-12-25 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20201225_1038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoughtItem',
        ),
    ]
