# Generated by Django 3.1.3 on 2020-12-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_boughtitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtitem',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
